spring.application.name=lolparser

spring.jackson.property-naming-strategy=${SPRING_JACKSON_PROPERTY_NAMING_STRATEGY:SNAKE_CASE}

server.port=${SERVER_PORT:8080}
spring.rabbitmq.port=${RABBIT_PORT:5672}
spring.rabbitmq.host=${RABBIT_HOST:localhost}
spring.rabbitmq.username=${RABBIT_USER:guest}
spring.rabbitmq.password=${RABBIT_PASS:guest}

spring.rabbitmq.exchange=form.exchange
form.service.url=${FORM_SERVICE_URL:http://localhost:5004}

spring.rabbitmq.bindings[0].queue=form.all.queue
spring.rabbitmq.bindings[0].routing-key=form.*
spring.rabbitmq.bindings[0].durable=true


spring.rabbitmq.bindings[1].queue=form.account.queue
spring.rabbitmq.bindings[1].routing-key=form.account
spring.rabbitmq.bindings[1].durable=true
