spring.application.name=${APP_NAME:SearchFormService}
spring.mongodb.uri=${MONGO_URI:mongodb://localhost:27017/sfs}
spring.data.mongodb.field-naming-strategy=${SPRING_DATA_MONGODB_FIELD_NAMING_STRATEGY:org.springframework.data.mapping.model.SnakeCaseFieldNamingStrategy}
spring.jackson.property-naming-strategy=${SPRING_JACKSON_PROPERTY_NAMING_STRATEGY:SNAKE_CASE}

server.port=${SERVER_PORT:8080}
spring.rabbitmq.port=${RABBIT_PORT:5672}
spring.rabbitmq.host=${RABBIT_HOST:localhost}
spring.rabbitmq.username=${RABBIT_USER:guest}
spring.rabbitmq.password=${RABBIT_PASS:guest}

spring.rabbitmq.exchange=form.exchange


spring.rabbitmq.bindings[0].queue=form.all.queue
spring.rabbitmq.bindings[0].routing-key=form.*
spring.rabbitmq.bindings[0].durable=true



spring.rabbitmq.bindings[1].queue=log.queue
spring.rabbitmq.bindings[1].routing-key=log.*
spring.rabbitmq.bindings[1].durable=true

spring.rabbitmq.bindings[2].queue=form.matched.queue
spring.rabbitmq.bindings[2].routing-key=form.matched
spring.rabbitmq.bindings[2].durable=true


spring.rabbitmq.bindings[3].queue=form.account.queue
spring.rabbitmq.bindings[3].routing-key=form.account
spring.rabbitmq.bindings[3].durable=true


spring.rabbitmq.bindings[4].queue=form.user.queue
spring.rabbitmq.bindings[4].routing-key=form.user
spring.rabbitmq.bindings[4].durable=true