spring.application.name=SearchFormService
spring.mongodb.uri=mongodb://mongodb:27017/sfs
spring.data.mongodb.field-naming-strategy=org.springframework.data.mapping.model.SnakeCaseFieldNamingStrategy
spring.jackson.property-naming-strategy=SNAKE_CASE
notificator.url=https://notificator:5000
