spring.application.name=${APP_NAME:FormConsumer}
spring.jackson.property-naming-strategy=${SPRING_JACKSON_PROPERTY_NAMING_STRATEGY:SNAKE_CASE}


notification.service.url=${NOTIFICATION_SERVICE_URL:http://localhost:5003}
user.service.url=${USER_SERVICE_URL:http://localhost:5002}
spring.rabbitmq.port=${RABBIT_PORT:5672}
spring.rabbitmq.host=${RABBIT_HOST:localhost}
spring.rabbitmq.username=${RABBIT_USER:guest}
spring.rabbitmq.password=${RABBIT_PASS:guest}

spring.rabbitmq.exchange=form.exchange


spring.rabbitmq.bindings[0].queue=form.all.queue
spring.rabbitmq.bindings[0].routing-key=form.*
spring.rabbitmq.bindings[0].durable=true



spring.rabbitmq.bindings[1].queue=log.queue
spring.rabbitmq.bindings[1].routing-key=log.*
spring.rabbitmq.bindings[1].durable=true

spring.rabbitmq.bindings[2].queue=form.matched.queue
spring.rabbitmq.bindings[2].routing-key=form.matched
spring.rabbitmq.bindings[2].durable=true