spring.data.mongodb.uri=mongodb://mongodb:27017/notifierdb
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.info.title=Notifier Service API
springdoc.info.version=1.0
springdoc.info.description=API documentation for the Notification Service
telegram.bot.token=7715541625:AAFkoVyrNhJj9_bb6mp8ri_k1B5TBFFAxK0
telegram.bot.username=@SpeechToTextVictoria_Bot
SMTP_PORT=587
SMTP_SERVER=smtp.gmail.com
EMAIL_ADDRESS=akioralol@gmail.com
EMAIL_PASSWORD=dbmm vkex blxh qwyy
server.port=${SERVER_PORT:8080}
user.service.url=${USER_SERVICE_URL:http://localhost:5002}
notification.service.url=${NOTIFICATION_SERVICE_URL:http://localhost:5003}

spring.rabbitmq.host=${RABBIT_HOST:localhost}
spring.rabbitmq.port=${RABBIT_PORT:5672}
spring.rabbitmq.username=${RABBIT_USER:guest}
spring.rabbitmq.password=${RABBIT_PASS:guest}
spring.rabbitmq.exchange=notification.exchange

spring.rabbitmq.bindings[0].queue=notification.queue
spring.rabbitmq.bindings[0].routing-key=notification.*
spring.rabbitmq.bindings[0].durable=true

# Разрешить все origins
spring.mvc.cors.allowed-origins=*
# Разрешить все методы
spring.mvc.cors.allowed-methods=*
# Разрешить все заголовки
spring.mvc.cors.allowed-headers=*
# Разрешить учетные данные (false для всех origins)
spring.mvc.cors.allow-credentials=false
# Время кэширования
spring.mvc.cors.max-age=3600
