spring.data.mongodb.uri=mongodb://mongo:27017/notifierdb
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.info.title=Notifier Service API
springdoc.info.version=1.0
springdoc.info.description=API documentation for the Notification Service
telegram.bot.token=7715541625:AAFkoVyrNhJj9_bb6mp8ri_k1B5TBFFAxK0
telegram.bot.username=@SpeechToTextVictoria_Bot
SMTP_PORT=587
SMTP_SERVER=smtp.gmail.com
EMAIL_ADDRESS=akioralol@gmail.com
EMAIL_PASSWORD=dbmm vkex blxh qwyy